const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const sandbox={btoa,atob,Float32Array,Uint8Array,DataView};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/js/voice-packets.js'),'utf8'),sandbox);
const P=sandbox.EclipseVoicePackets;
const tone=Float32Array.from({length:800},(_,i)=>.5*Math.sin(i*2*Math.PI*440/8000));
const wire=P.encode(tone,7), decoded=P.decode(wire);
assert.equal(decoded.seq,7);assert.equal(decoded.samples.length,800);
assert.ok(Math.max(...tone.map((v,i)=>Math.abs(v-decoded.samples[i])))<1/32767);
assert.equal(P.decode('bad'),null);assert.equal(P.decode(wire.slice(1)),null);
let now=0;const played=[];const q=new P.JitterBuffer(()=>now,(samples,time)=>played.push({samples,time}));
const f=n=>P.decode(P.encode(tone,n));
assert.ok(q.push(f(0)));now=.1;assert.ok(q.push(f(2)));assert.ok(q.push(f(1)));
assert.equal(q.push(f(1)),false);assert.equal(q.push(f(10000)),false);
for(now=.12;now<.5;now+=.02)q.pump();
assert.equal(played.length,3);assert.ok(Math.abs(played[0].time-.15)<.001);
assert.ok(Math.abs(played[2].time-.35)<.001);
assert.equal(q.push(f(0)),false);
now=3;assert.ok(q.push(f(3)));now=3.12;q.pump();assert.equal(played.length,4);
q.reset();assert.equal(q.frames.size,0);
console.log(JSON.stringify({status:'PASS',codec:'PCM16LE/8000/mono',frameBytes:P.BYTES,base64Chars:wire.length,fakeClockInitialBufferMs:150,roundtrip:true,reorder:true,duplicatesRejected:true,boundedQueue:true,idleRecovery:true,realNetworkLatency:'NOT MEASURED'}));
